name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    # ---------------------------------
    # SECURITY (GitLab SAST + Secrets)
    # ---------------------------------
    security:
        name: Security Scan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # Secret detection
            - name: Scan for secrets (Gitleaks)
              uses: gitleaks/gitleaks-action@v2

            # SAST
            - name: Run Semgrep SAST
              uses: returntocorp/semgrep-action@v1
              with:
                  config: p/default

    # ---------------------------------
    # BUILD
    # ---------------------------------
    build:
        name: Build .NET
        runs-on: ubuntu-latest
        needs: security

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "10.0.x"

            - name: Restore
              run: dotnet restore ServiceDesk/ServiceDesk.slnx

            - name: Lint
              run: dotnet format ServiceDesk/ServiceDesk.slnx --verify-no-changes --severity info

            - name: Build
              run: dotnet build ServiceDesk/ServiceDesk.slnx --configuration Release --no-restore
