name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    # ---------------------------------
    # SECURITY (GitLab SAST + Secrets)
    # ---------------------------------
    security:
        name: Security Scan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                config: p/default
                exclude: docker-compose.yml

            # Secret detection
            - name: Scan for secrets (Gitleaks)
              uses: gitleaks/gitleaks-action@v2

            # SAST
            - name: Run Semgrep SAST
              uses: returntocorp/semgrep-action@v1
              with:
                  config: p/default


    # ---------------------------------
    # BUILD
    # ---------------------------------
    build:
      name: Build .NET
      runs-on: ubuntu-latest
      needs: security
    
      steps:
        - uses: actions/checkout@v4
    
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
    
        - name: Restore
          run: dotnet restore ServiceDesk/ServiceDesk.slnx
    
        - name: Build
          run: dotnet build ServiceDesk/ServiceDesk.slnx -c Release --no-restore
    
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-output
            path: "**/bin/Release/**"


    # ---------------------------------
    # TEST
    # ---------------------------------
    test:
      name: Run Tests
      runs-on: ubuntu-latest
      needs: build
    
      steps:
        - uses: actions/checkout@v4
    
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
    
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-output
    
        - name: Run tests
          run: dotnet test ServiceDesk/ServiceDesk.slnx -c Release --no-build --logger "trx"


